import { Category, Product } from "../../src/lib/db/models/index.js";

type SeedVariant = {
  name: string;
  sku: string;
  price: number;
  comparePrice?: number;
  stock: number;
};

type SeedRating = {
  avg: number;
  count: number;
};

type SeedProduct = {
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  categorySlug: string;
  brand: string;
  basePrice: number;
  comparePrice?: number;
  tags: string[];
  badges: string[];
  skinTypes?: string[];
  ingredients?: string[];
  allergens?: string[];
  variants: SeedVariant[];
  imageSeeds?: number;
  rating: SeedRating;
  totalSold: number;
  isFeatured?: boolean;
};

// Prices are integer paisa. 1 BDT = 100 paisa. e.g. 125000 = 1250 BDT.
// Every product also carries deterministic rating / totalSold so the seed is reproducible
// across CI runs and preview environments.
const productEntries: SeedProduct[] = [
  // ── Lipstick ────────────────────────────────────────────────────────────────
  {
    name: "Velvet Matte Lipstick",
    slug: "velvet-matte-lipstick",
    description: "A weightless, long-wearing matte lipstick with a velvety finish.",
    shortDescription: "Long-wearing matte lipstick",
    categorySlug: "lipstick",
    brand: "GlowCart",
    basePrice: 85000,
    comparePrice: 99000,
    tags: ["lipstick", "matte", "bestseller"],
    badges: ["bestseller"],
    variants: [
      { name: "Rose Noir", sku: "VML-ROSE-01", price: 85000, stock: 120 },
      { name: "Cherry Bomb", sku: "VML-CHERRY-02", price: 85000, stock: 80 },
      { name: "Mocha", sku: "VML-MOCHA-03", price: 85000, stock: 60 },
    ],
    imageSeeds: 3,
    rating: { avg: 4.7, count: 312 },
    totalSold: 2450,
    isFeatured: true,
  },
  {
    name: "Hydra Glow Lip Tint",
    slug: "hydra-glow-lip-tint",
    description: "Buildable sheer tint with hyaluronic acid for all-day hydration.",
    shortDescription: "Hydrating sheer lip tint",
    categorySlug: "lipstick",
    brand: "GlowCart",
    basePrice: 65000,
    tags: ["lipstick", "tint", "hydrating"],
    badges: ["new"],
    variants: [
      { name: "Peach Sorbet", sku: "HGL-PEACH-01", price: 65000, stock: 150 },
      { name: "Berry Crush", sku: "HGL-BERRY-02", price: 65000, stock: 120 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 148 },
    totalSold: 1020,
  },
  {
    name: "Saffron Silk Lip Balm",
    slug: "saffron-silk-lip-balm",
    description: "Nourishing tinted balm infused with saffron and almond oil.",
    shortDescription: "Saffron-infused tinted balm",
    categorySlug: "lipstick",
    brand: "Saffron & Rose",
    basePrice: 48000,
    tags: ["lipstick", "balm", "nourishing"],
    badges: [],
    skinTypes: ["dry", "sensitive"],
    variants: [
      { name: "Rosewood", sku: "SSLB-ROSE", price: 48000, stock: 95 },
      { name: "Nude Plum", sku: "SSLB-PLUM", price: 48000, stock: 60 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.3, count: 78 },
    totalSold: 640,
  },
  {
    name: "Kohl Midnight Liquid Lip",
    slug: "kohl-midnight-liquid-lip",
    description: "High-pigment liquid lip with a dramatic matte finish for evening looks.",
    shortDescription: "Dramatic liquid lip matte",
    categorySlug: "lipstick",
    brand: "Kohl",
    basePrice: 72000,
    comparePrice: 88000,
    tags: ["lipstick", "liquid", "matte"],
    badges: ["limited"],
    variants: [
      { name: "Noir", sku: "KML-NOIR", price: 72000, stock: 45 },
      { name: "Oxblood", sku: "KML-OXBLD", price: 72000, stock: 30 },
      { name: "Bare", sku: "KML-BARE", price: 72000, stock: 55 },
    ],
    imageSeeds: 3,
    rating: { avg: 4.6, count: 201 },
    totalSold: 1380,
  },
  {
    name: "Aurum Sheer Gloss",
    slug: "aurum-sheer-gloss",
    description: "Non-sticky shimmer gloss with a mirror finish and plumping peptides.",
    shortDescription: "Plumping mirror gloss",
    categorySlug: "lipstick",
    brand: "Aurum",
    basePrice: 55000,
    tags: ["lipstick", "gloss", "shimmer"],
    badges: ["new"],
    variants: [
      { name: "Champagne", sku: "AUG-CHMP", price: 55000, stock: 110 },
      { name: "Rose Gold", sku: "AUG-RGLD", price: 55000, stock: 90 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.4, count: 94 },
    totalSold: 720,
  },
  {
    name: "Lumen Satin Lipstick Duo",
    slug: "lumen-satin-lipstick-duo",
    description: "A pair of complementary satin lipsticks for day-to-night wear.",
    shortDescription: "Satin lipstick duo set",
    categorySlug: "lipstick",
    brand: "Lumen",
    basePrice: 98000,
    comparePrice: 120000,
    tags: ["lipstick", "satin", "set"],
    badges: ["giftable"],
    variants: [{ name: "Rose + Berry", sku: "LSLD-RB", price: 98000, stock: 40 }],
    imageSeeds: 2,
    rating: { avg: 4.8, count: 167 },
    totalSold: 980,
  },

  // ── Foundation ──────────────────────────────────────────────────────────────
  {
    name: "Silk Finish Liquid Foundation",
    slug: "silk-finish-liquid-foundation",
    description: "Medium-coverage liquid foundation with a natural satin finish.",
    shortDescription: "24-hour satin finish foundation",
    categorySlug: "foundation",
    brand: "Lumen",
    basePrice: 185000,
    comparePrice: 225000,
    tags: ["foundation", "liquid", "medium-coverage"],
    badges: ["bestseller"],
    skinTypes: ["normal", "combination"],
    variants: [
      { name: "Porcelain 01", sku: "SFLF-01", price: 185000, stock: 40 },
      { name: "Ivory 02", sku: "SFLF-02", price: 185000, stock: 60 },
      { name: "Beige 03", sku: "SFLF-03", price: 185000, stock: 55 },
    ],
    imageSeeds: 3,
    rating: { avg: 4.6, count: 289 },
    totalSold: 2180,
    isFeatured: true,
  },
  {
    name: "AirWeight Powder Foundation",
    slug: "airweight-powder-foundation",
    description: "Breathable pressed powder foundation, buildable to full coverage.",
    shortDescription: "Breathable pressed powder",
    categorySlug: "foundation",
    brand: "Lumen",
    basePrice: 145000,
    tags: ["foundation", "powder"],
    badges: [],
    skinTypes: ["oily", "combination"],
    variants: [
      { name: "Light", sku: "AWPF-LT", price: 145000, stock: 30 },
      { name: "Medium", sku: "AWPF-MD", price: 145000, stock: 30 },
      { name: "Deep", sku: "AWPF-DP", price: 145000, stock: 30 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.2, count: 134 },
    totalSold: 870,
  },
  {
    name: "DewDrop Serum Foundation",
    slug: "dewdrop-serum-foundation",
    description: "Lightweight serum-foundation hybrid with niacinamide and peptides.",
    shortDescription: "Serum foundation with niacinamide",
    categorySlug: "foundation",
    brand: "Aurum",
    basePrice: 215000,
    comparePrice: 260000,
    tags: ["foundation", "serum", "dewy"],
    badges: ["new"],
    skinTypes: ["dry", "normal"],
    ingredients: ["Niacinamide", "Peptides", "Hyaluronic Acid"],
    variants: [
      { name: "Fair", sku: "DSF-FAIR", price: 215000, stock: 35 },
      { name: "Warm Beige", sku: "DSF-WBG", price: 215000, stock: 40 },
      { name: "Tan", sku: "DSF-TAN", price: 215000, stock: 30 },
    ],
    imageSeeds: 3,
    rating: { avg: 4.7, count: 198 },
    totalSold: 1420,
  },
  {
    name: "Saffron & Rose Cushion Compact",
    slug: "saffron-rose-cushion-compact",
    description: "Korean-style cushion compact with SPF 50 and rose extract.",
    shortDescription: "Cushion compact with SPF 50",
    categorySlug: "foundation",
    brand: "Saffron & Rose",
    basePrice: 175000,
    tags: ["foundation", "cushion", "spf"],
    badges: ["bestseller"],
    skinTypes: ["normal", "dry"],
    variants: [
      { name: "01 Ivory", sku: "SRCC-01", price: 175000, stock: 50 },
      { name: "02 Natural", sku: "SRCC-02", price: 175000, stock: 55 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 176 },
    totalSold: 1310,
  },
  {
    name: "Kohl Matte Velvet Foundation",
    slug: "kohl-matte-velvet-foundation",
    description: "Full-coverage matte foundation for oily and combination skin.",
    shortDescription: "Full-coverage matte liquid",
    categorySlug: "foundation",
    brand: "Kohl",
    basePrice: 165000,
    tags: ["foundation", "matte", "full-coverage"],
    badges: [],
    skinTypes: ["oily", "combination"],
    variants: [
      { name: "03 Sand", sku: "KMVF-03", price: 165000, stock: 35 },
      { name: "05 Honey", sku: "KMVF-05", price: 165000, stock: 40 },
      { name: "07 Cocoa", sku: "KMVF-07", price: 165000, stock: 25 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.3, count: 112 },
    totalSold: 790,
  },

  // ── Skincare ────────────────────────────────────────────────────────────────
  {
    name: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    description: "15% stabilized vitamin C serum for visibly brighter, even-toned skin.",
    shortDescription: "Daily brightening serum",
    categorySlug: "skincare",
    brand: "GlowCart",
    basePrice: 215000,
    comparePrice: 250000,
    tags: ["serum", "vitamin-c", "brightening"],
    badges: ["bestseller"],
    ingredients: ["Ascorbic Acid", "Ferulic Acid", "Vitamin E"],
    skinTypes: ["normal", "dry", "combination"],
    variants: [
      { name: "30 ml", sku: "VCBS-30", price: 215000, stock: 90 },
      { name: "50 ml", sku: "VCBS-50", price: 320000, stock: 40 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.8, count: 402 },
    totalSold: 3210,
    isFeatured: true,
  },
  {
    name: "Ceramide Barrier Repair Cream",
    slug: "ceramide-barrier-repair-cream",
    description: "Rich ceramide-packed cream to restore the skin barrier overnight.",
    shortDescription: "Overnight barrier repair cream",
    categorySlug: "skincare",
    brand: "GlowCart",
    basePrice: 195000,
    tags: ["moisturizer", "ceramide", "barrier"],
    badges: [],
    skinTypes: ["dry", "sensitive"],
    variants: [{ name: "50 ml", sku: "CBRC-50", price: 195000, stock: 70 }],
    imageSeeds: 2,
    rating: { avg: 4.6, count: 245 },
    totalSold: 1780,
  },
  {
    name: "Gentle Foaming Cleanser",
    slug: "gentle-foaming-cleanser",
    description: "pH-balanced foaming cleanser with green tea and centella.",
    shortDescription: "pH-balanced daily cleanser",
    categorySlug: "skincare",
    brand: "GlowCart",
    basePrice: 75000,
    tags: ["cleanser", "foaming", "daily"],
    badges: ["bestseller"],
    ingredients: ["Green Tea Extract", "Centella Asiatica", "Glycerin"],
    skinTypes: ["normal", "oily", "combination", "sensitive"],
    variants: [{ name: "150 ml", sku: "GFC-150", price: 75000, stock: 140 }],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 356 },
    totalSold: 2640,
  },
  {
    name: "Niacinamide 10% Pore Serum",
    slug: "niacinamide-10-pore-serum",
    description: "High-strength niacinamide serum to minimize pores and balance sebum.",
    shortDescription: "Pore-refining niacinamide serum",
    categorySlug: "skincare",
    brand: "Lumen",
    basePrice: 95000,
    tags: ["serum", "niacinamide", "pores"],
    badges: ["new"],
    ingredients: ["Niacinamide", "Zinc PCA"],
    skinTypes: ["oily", "combination"],
    variants: [{ name: "30 ml", sku: "N10-30", price: 95000, stock: 110 }],
    imageSeeds: 2,
    rating: { avg: 4.4, count: 187 },
    totalSold: 1490,
  },
  {
    name: "Retinol 0.5 Renewal Oil",
    slug: "retinol-05-renewal-oil",
    description: "Encapsulated retinol in a soothing squalane base — beginner friendly.",
    shortDescription: "Gentle overnight retinol oil",
    categorySlug: "skincare",
    brand: "Aurum",
    basePrice: 285000,
    comparePrice: 340000,
    tags: ["retinol", "anti-aging", "night"],
    badges: ["limited"],
    ingredients: ["Encapsulated Retinol", "Squalane", "Bakuchiol"],
    skinTypes: ["normal", "dry"],
    variants: [{ name: "30 ml", sku: "R05-30", price: 285000, stock: 45 }],
    imageSeeds: 2,
    rating: { avg: 4.7, count: 164 },
    totalSold: 890,
  },
  {
    name: "Rose Hydration Toner",
    slug: "rose-hydration-toner",
    description: "Alcohol-free toner with damask rose water and hyaluronic acid.",
    shortDescription: "Hydrating rose water toner",
    categorySlug: "skincare",
    brand: "Saffron & Rose",
    basePrice: 88000,
    tags: ["toner", "rose", "hydrating"],
    badges: [],
    ingredients: ["Damask Rose Water", "Hyaluronic Acid", "Panthenol"],
    skinTypes: ["dry", "sensitive", "normal"],
    variants: [{ name: "200 ml", sku: "RHT-200", price: 88000, stock: 100 }],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 211 },
    totalSold: 1620,
  },
  {
    name: "AHA+BHA Clarifying Peel",
    slug: "aha-bha-clarifying-peel",
    description: "Weekly exfoliating peel with lactic, glycolic and salicylic acid.",
    shortDescription: "Weekly exfoliating peel",
    categorySlug: "skincare",
    brand: "Lumen",
    basePrice: 168000,
    tags: ["exfoliant", "aha", "bha", "peel"],
    badges: [],
    ingredients: ["Lactic Acid", "Glycolic Acid", "Salicylic Acid"],
    skinTypes: ["oily", "combination", "normal"],
    allergens: ["salicylates"],
    variants: [{ name: "50 ml", sku: "ABP-50", price: 168000, stock: 60 }],
    imageSeeds: 2,
    rating: { avg: 4.3, count: 128 },
    totalSold: 760,
  },
  {
    name: "SPF 50 Invisible Sunscreen",
    slug: "spf-50-invisible-sunscreen",
    description: "No-white-cast broad-spectrum daily sunscreen for all skin tones.",
    shortDescription: "Daily invisible SPF 50",
    categorySlug: "skincare",
    brand: "GlowCart",
    basePrice: 125000,
    tags: ["sunscreen", "spf", "daily"],
    badges: ["bestseller"],
    skinTypes: ["normal", "oily", "combination", "sensitive", "dry"],
    variants: [{ name: "50 ml", sku: "SPF50-50", price: 125000, stock: 180 }],
    imageSeeds: 2,
    rating: { avg: 4.7, count: 389 },
    totalSold: 3100,
    isFeatured: true,
  },
  {
    name: "Overnight Sleeping Mask",
    slug: "overnight-sleeping-mask",
    description: "Gel-cream sleeping mask with snow mushroom for plump morning skin.",
    shortDescription: "Plumping gel sleeping mask",
    categorySlug: "skincare",
    brand: "Aurum",
    basePrice: 155000,
    tags: ["mask", "sleeping", "hydrating"],
    badges: [],
    skinTypes: ["dry", "normal"],
    variants: [{ name: "80 ml", sku: "OSM-80", price: 155000, stock: 75 }],
    imageSeeds: 2,
    rating: { avg: 4.4, count: 142 },
    totalSold: 910,
  },

  // ── Fragrance ───────────────────────────────────────────────────────────────
  {
    name: "Rose Petal Eau de Parfum",
    slug: "rose-petal-eau-de-parfum",
    description: "A modern rose fragrance layered with musk and white tea.",
    shortDescription: "Rose · musk · white tea",
    categorySlug: "fragrance",
    brand: "Saffron & Rose",
    basePrice: 350000,
    comparePrice: 420000,
    tags: ["fragrance", "rose", "edp"],
    badges: ["featured"],
    variants: [
      { name: "50 ml", sku: "RPEP-50", price: 350000, stock: 25 },
      { name: "100 ml", sku: "RPEP-100", price: 520000, stock: 15 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.8, count: 221 },
    totalSold: 1040,
    isFeatured: true,
  },
  {
    name: "Oud Noir Body Mist",
    slug: "oud-noir-body-mist",
    description: "Lightweight body mist with warm oud and amber notes.",
    shortDescription: "Oud · amber body mist",
    categorySlug: "fragrance",
    brand: "Kohl",
    basePrice: 125000,
    tags: ["body-mist", "oud"],
    badges: [],
    variants: [{ name: "150 ml", sku: "ONBM-150", price: 125000, stock: 50 }],
    imageSeeds: 2,
    rating: { avg: 4.3, count: 98 },
    totalSold: 680,
  },
  {
    name: "Aurum Gold Elixir Parfum",
    slug: "aurum-gold-elixir-parfum",
    description: "A luxurious parfum with saffron, jasmine and sandalwood.",
    shortDescription: "Saffron · jasmine · sandalwood",
    categorySlug: "fragrance",
    brand: "Aurum",
    basePrice: 460000,
    comparePrice: 550000,
    tags: ["fragrance", "parfum", "luxury"],
    badges: ["limited"],
    variants: [{ name: "75 ml", sku: "AGE-75", price: 460000, stock: 20 }],
    imageSeeds: 2,
    rating: { avg: 4.9, count: 156 },
    totalSold: 520,
    isFeatured: true,
  },
  {
    name: "Citrus Bloom EDT",
    slug: "citrus-bloom-edt",
    description: "A fresh unisex eau de toilette with bergamot, neroli and white musk.",
    shortDescription: "Fresh citrus unisex EDT",
    categorySlug: "fragrance",
    brand: "Lumen",
    basePrice: 240000,
    tags: ["fragrance", "edt", "citrus", "unisex"],
    badges: ["new"],
    variants: [
      { name: "50 ml", sku: "CBE-50", price: 240000, stock: 40 },
      { name: "100 ml", sku: "CBE-100", price: 360000, stock: 25 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.4, count: 118 },
    totalSold: 760,
  },
  {
    name: "Velvet Night Travel Spray",
    slug: "velvet-night-travel-spray",
    description: "Pocket-sized travel spray with vanilla, tonka and cashmere wood.",
    shortDescription: "Refillable travel spray",
    categorySlug: "fragrance",
    brand: "GlowCart",
    basePrice: 98000,
    tags: ["fragrance", "travel"],
    badges: ["giftable"],
    variants: [{ name: "10 ml", sku: "VNTS-10", price: 98000, stock: 80 }],
    imageSeeds: 2,
    rating: { avg: 4.2, count: 74 },
    totalSold: 510,
  },
  {
    name: "Saffron Amber Solid Perfume",
    slug: "saffron-amber-solid-perfume",
    description: "Portable solid perfume balm with warm amber and saffron.",
    shortDescription: "Solid perfume balm",
    categorySlug: "fragrance",
    brand: "Saffron & Rose",
    basePrice: 68000,
    tags: ["fragrance", "solid", "amber"],
    badges: [],
    variants: [{ name: "15 g", sku: "SASP-15", price: 68000, stock: 60 }],
    imageSeeds: 2,
    rating: { avg: 4.1, count: 52 },
    totalSold: 340,
  },

  // ── Eyes ────────────────────────────────────────────────────────────────────
  {
    name: "Smokey Eyeshadow Palette",
    slug: "smokey-eyeshadow-palette",
    description: "12-shade eyeshadow palette with mattes, shimmers and glitters.",
    shortDescription: "12-shade smokey palette",
    categorySlug: "eyes",
    brand: "GlowCart",
    basePrice: 175000,
    tags: ["eyeshadow", "palette"],
    badges: ["bestseller"],
    variants: [{ name: "Standard", sku: "SEP-12", price: 175000, stock: 35 }],
    imageSeeds: 2,
    rating: { avg: 4.6, count: 224 },
    totalSold: 1480,
  },
  {
    name: "Precision Liquid Eyeliner",
    slug: "precision-liquid-eyeliner",
    description: "Ultra-fine tip liquid eyeliner, waterproof and smudge-proof.",
    shortDescription: "Waterproof liquid liner",
    categorySlug: "eyes",
    brand: "GlowCart",
    basePrice: 55000,
    tags: ["eyeliner", "waterproof"],
    badges: [],
    variants: [
      { name: "Jet Black", sku: "PLE-BLK", price: 55000, stock: 120 },
      { name: "Brown", sku: "PLE-BRN", price: 55000, stock: 60 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 201 },
    totalSold: 1620,
  },
  {
    name: "Volumizing Mascara",
    slug: "volumizing-mascara",
    description: "Buildable volume mascara with a hourglass brush for clump-free lashes.",
    shortDescription: "Clump-free volume mascara",
    categorySlug: "eyes",
    brand: "Lumen",
    basePrice: 68000,
    tags: ["mascara", "volume"],
    badges: ["bestseller"],
    variants: [
      { name: "Intense Black", sku: "VM-INT", price: 68000, stock: 140 },
      { name: "Brown", sku: "VM-BRN", price: 68000, stock: 70 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 267 },
    totalSold: 2040,
  },
  {
    name: "Kohl Intense Kajal Pencil",
    slug: "kohl-intense-kajal-pencil",
    description: "Deeply pigmented kajal pencil with a smudge-proof 16-hour formula.",
    shortDescription: "16-hour smudge-proof kajal",
    categorySlug: "eyes",
    brand: "Kohl",
    basePrice: 42000,
    tags: ["kajal", "eyeliner"],
    badges: ["bestseller"],
    variants: [{ name: "Midnight Black", sku: "KIK-MB", price: 42000, stock: 180 }],
    imageSeeds: 2,
    rating: { avg: 4.7, count: 312 },
    totalSold: 3040,
    isFeatured: true,
  },
  {
    name: "Nude Essentials Eyeshadow Palette",
    slug: "nude-essentials-eyeshadow-palette",
    description: "9 wearable nude shades ideal for daily looks and everyday wear.",
    shortDescription: "9-shade daily nude palette",
    categorySlug: "eyes",
    brand: "Aurum",
    basePrice: 135000,
    comparePrice: 160000,
    tags: ["eyeshadow", "palette", "nude"],
    badges: ["new"],
    variants: [{ name: "Standard", sku: "NEP-09", price: 135000, stock: 50 }],
    imageSeeds: 2,
    rating: { avg: 4.4, count: 143 },
    totalSold: 860,
  },
  {
    name: "Brow Precision Gel",
    slug: "brow-precision-gel",
    description: "Tinted brow gel with micro-fibers for defined, natural-looking brows.",
    shortDescription: "Tinted fiber brow gel",
    categorySlug: "eyes",
    brand: "GlowCart",
    basePrice: 58000,
    tags: ["brow", "gel"],
    badges: [],
    variants: [
      { name: "Taupe", sku: "BPG-TP", price: 58000, stock: 80 },
      { name: "Dark Brown", sku: "BPG-DBR", price: 58000, stock: 85 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.3, count: 109 },
    totalSold: 740,
  },

  // ── Brushes ─────────────────────────────────────────────────────────────────
  {
    name: "Pro Brush Set 10-Piece",
    slug: "pro-brush-set-10-piece",
    description: "Complete 10-piece synthetic brush set with travel pouch.",
    shortDescription: "10-piece synthetic brush set",
    categorySlug: "brushes",
    brand: "GlowCart",
    basePrice: 295000,
    comparePrice: 350000,
    tags: ["brushes", "set"],
    badges: ["new"],
    variants: [{ name: "Standard", sku: "PBS-10", price: 295000, stock: 25 }],
    imageSeeds: 2,
    rating: { avg: 4.6, count: 132 },
    totalSold: 580,
  },
  {
    name: "Foundation Buffing Brush",
    slug: "foundation-buffing-brush",
    description: "Dense synthetic buffer for seamless liquid foundation application.",
    shortDescription: "Dense buffing foundation brush",
    categorySlug: "brushes",
    brand: "GlowCart",
    basePrice: 85000,
    tags: ["brush", "foundation"],
    badges: [],
    variants: [{ name: "Standard", sku: "FBB-01", price: 85000, stock: 110 }],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 94 },
    totalSold: 620,
  },
  {
    name: "Angled Blush Brush",
    slug: "angled-blush-brush",
    description: "Tapered angled brush for precise blush and contour placement.",
    shortDescription: "Angled blush & contour brush",
    categorySlug: "brushes",
    brand: "Lumen",
    basePrice: 68000,
    tags: ["brush", "blush", "contour"],
    badges: [],
    variants: [{ name: "Standard", sku: "ABB-01", price: 68000, stock: 95 }],
    imageSeeds: 2,
    rating: { avg: 4.3, count: 71 },
    totalSold: 430,
  },
  {
    name: "Fan Highlighter Brush",
    slug: "fan-highlighter-brush",
    description: "Ultra-soft fan brush for precise, airy highlighter application.",
    shortDescription: "Soft fan highlighter brush",
    categorySlug: "brushes",
    brand: "Aurum",
    basePrice: 72000,
    tags: ["brush", "highlighter"],
    badges: [],
    variants: [{ name: "Standard", sku: "FHB-01", price: 72000, stock: 75 }],
    imageSeeds: 2,
    rating: { avg: 4.2, count: 58 },
    totalSold: 310,
  },
  {
    name: "Eye Essentials Brush Trio",
    slug: "eye-essentials-brush-trio",
    description: "Three essential eye brushes: flat shader, blending and smudger.",
    shortDescription: "3-piece essential eye brush set",
    categorySlug: "brushes",
    brand: "Kohl",
    basePrice: 115000,
    comparePrice: 135000,
    tags: ["brush", "eye", "set"],
    badges: ["giftable"],
    variants: [{ name: "Standard", sku: "EEBT-3", price: 115000, stock: 60 }],
    imageSeeds: 2,
    rating: { avg: 4.4, count: 86 },
    totalSold: 470,
  },
  {
    name: "Silicone Blender Sponge",
    slug: "silicone-blender-sponge",
    description: "Reusable silicone blender for streak-free foundation application.",
    shortDescription: "Reusable silicone blender",
    categorySlug: "brushes",
    brand: "GlowCart",
    basePrice: 38000,
    tags: ["sponge", "blender"],
    badges: [],
    variants: [{ name: "Pink", sku: "SBS-PK", price: 38000, stock: 200 }],
    imageSeeds: 2,
    rating: { avg: 4.1, count: 63 },
    totalSold: 520,
  },

  // ── Haircare ────────────────────────────────────────────────────────────────
  {
    name: "Argan Repair Hair Mask",
    slug: "argan-repair-hair-mask",
    description: "Deep conditioning hair mask with argan oil and keratin.",
    shortDescription: "Weekly repair hair mask",
    categorySlug: "haircare",
    brand: "Saffron & Rose",
    basePrice: 135000,
    tags: ["haircare", "mask", "argan"],
    badges: [],
    ingredients: ["Argan Oil", "Hydrolyzed Keratin", "Shea Butter"],
    variants: [{ name: "200 ml", sku: "ARHM-200", price: 135000, stock: 80 }],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 142 },
    totalSold: 990,
  },
  {
    name: "Rosemary Scalp Serum",
    slug: "rosemary-scalp-serum",
    description: "Lightweight scalp serum with rosemary oil and caffeine for fuller hair.",
    shortDescription: "Scalp serum with rosemary",
    categorySlug: "haircare",
    brand: "GlowCart",
    basePrice: 155000,
    comparePrice: 185000,
    tags: ["haircare", "scalp", "serum"],
    badges: ["new"],
    ingredients: ["Rosemary Leaf Extract", "Caffeine", "Biotin"],
    variants: [{ name: "100 ml", sku: "RSS-100", price: 155000, stock: 65 }],
    imageSeeds: 2,
    rating: { avg: 4.6, count: 178 },
    totalSold: 1240,
  },
  {
    name: "Sulfate-Free Daily Shampoo",
    slug: "sulfate-free-daily-shampoo",
    description: "Gentle sulfate-free shampoo for colored and chemically treated hair.",
    shortDescription: "Gentle sulfate-free shampoo",
    categorySlug: "haircare",
    brand: "Lumen",
    basePrice: 98000,
    tags: ["haircare", "shampoo", "sulfate-free"],
    badges: ["bestseller"],
    variants: [
      { name: "300 ml", sku: "SFDS-300", price: 98000, stock: 120 },
      { name: "500 ml", sku: "SFDS-500", price: 145000, stock: 60 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.4, count: 234 },
    totalSold: 1870,
  },
  {
    name: "Deep Moisture Conditioner",
    slug: "deep-moisture-conditioner",
    description: "Rich conditioner with shea butter and panthenol for dry hair.",
    shortDescription: "Rich daily conditioner",
    categorySlug: "haircare",
    brand: "Lumen",
    basePrice: 102000,
    tags: ["haircare", "conditioner"],
    badges: [],
    variants: [
      { name: "300 ml", sku: "DMC-300", price: 102000, stock: 95 },
      { name: "500 ml", sku: "DMC-500", price: 148000, stock: 50 },
    ],
    imageSeeds: 2,
    rating: { avg: 4.3, count: 156 },
    totalSold: 1130,
  },
  {
    name: "Heat Protection Mist",
    slug: "heat-protection-mist",
    description: "Thermal protection spray up to 230°C with argan and vitamin E.",
    shortDescription: "230°C heat shield spray",
    categorySlug: "haircare",
    brand: "Aurum",
    basePrice: 88000,
    tags: ["haircare", "styling", "heat"],
    badges: [],
    variants: [{ name: "150 ml", sku: "HPM-150", price: 88000, stock: 100 }],
    imageSeeds: 2,
    rating: { avg: 4.2, count: 102 },
    totalSold: 760,
  },
  {
    name: "Overnight Hair Oil",
    slug: "overnight-hair-oil",
    description: "Ayurvedic hair oil blend with bhringraj, amla and coconut.",
    shortDescription: "Ayurvedic overnight hair oil",
    categorySlug: "haircare",
    brand: "Saffron & Rose",
    basePrice: 92000,
    tags: ["haircare", "oil", "ayurvedic"],
    badges: ["bestseller"],
    ingredients: ["Bhringraj", "Amla", "Coconut Oil"],
    variants: [{ name: "200 ml", sku: "OHO-200", price: 92000, stock: 130 }],
    imageSeeds: 2,
    rating: { avg: 4.7, count: 289 },
    totalSold: 2240,
  },

  // ── Gifts ───────────────────────────────────────────────────────────────────
  {
    name: "Everyday Essentials Gift Box",
    slug: "everyday-essentials-gift-box",
    description: "Curated gift set with a lipstick, mini serum and fragrance sample.",
    shortDescription: "Curated beauty gift box",
    categorySlug: "gifts",
    brand: "GlowCart",
    basePrice: 275000,
    comparePrice: 325000,
    tags: ["gift", "bundle"],
    badges: ["giftable"],
    variants: [{ name: "Gift Box", sku: "EEGB-01", price: 275000, stock: 40 }],
    imageSeeds: 2,
    rating: { avg: 4.6, count: 167 },
    totalSold: 980,
    isFeatured: true,
  },
  {
    name: "Skin Ritual Starter Kit",
    slug: "skin-ritual-starter-kit",
    description: "Four-step routine: cleanser, toner, serum and moisturizer in travel sizes.",
    shortDescription: "4-step skincare starter",
    categorySlug: "gifts",
    brand: "GlowCart",
    basePrice: 320000,
    comparePrice: 395000,
    tags: ["gift", "skincare", "kit"],
    badges: ["giftable", "bestseller"],
    variants: [{ name: "Starter Kit", sku: "SRSK-01", price: 320000, stock: 30 }],
    imageSeeds: 2,
    rating: { avg: 4.7, count: 198 },
    totalSold: 1120,
  },
  {
    name: "Aurum Luxury Fragrance Set",
    slug: "aurum-luxury-fragrance-set",
    description: "Trio of signature fragrances in 15ml travel bottles, gift-wrapped.",
    shortDescription: "3-piece luxury fragrance set",
    categorySlug: "gifts",
    brand: "Aurum",
    basePrice: 350000,
    tags: ["gift", "fragrance", "luxury"],
    badges: ["giftable", "limited"],
    variants: [{ name: "Trio Set", sku: "ALFS-3", price: 350000, stock: 25 }],
    imageSeeds: 2,
    rating: { avg: 4.8, count: 104 },
    totalSold: 390,
  },
  {
    name: "Lumen Makeup Mini Kit",
    slug: "lumen-makeup-mini-kit",
    description: "Travel-size lipstick, mascara and blush in a magnetic case.",
    shortDescription: "Travel-size makeup trio",
    categorySlug: "gifts",
    brand: "Lumen",
    basePrice: 210000,
    comparePrice: 255000,
    tags: ["gift", "makeup", "travel"],
    badges: ["giftable"],
    variants: [{ name: "Mini Kit", sku: "LMMK-01", price: 210000, stock: 45 }],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 122 },
    totalSold: 680,
  },
  {
    name: "Rose Devotion Pamper Box",
    slug: "rose-devotion-pamper-box",
    description: "Body oil, hand cream and bath salts in a reusable rose-print box.",
    shortDescription: "Rose-themed pamper box",
    categorySlug: "gifts",
    brand: "Saffron & Rose",
    basePrice: 245000,
    tags: ["gift", "body", "spa"],
    badges: ["giftable"],
    variants: [{ name: "Pamper Box", sku: "RDPB-01", price: 245000, stock: 35 }],
    imageSeeds: 2,
    rating: { avg: 4.6, count: 88 },
    totalSold: 420,
  },
  {
    name: "Kohl Eye Icons Gift Set",
    slug: "kohl-eye-icons-gift-set",
    description: "Iconic eye set: kajal, mascara and liquid liner in a slim case.",
    shortDescription: "3-piece eye essentials set",
    categorySlug: "gifts",
    brand: "Kohl",
    basePrice: 158000,
    comparePrice: 190000,
    tags: ["gift", "eyes", "set"],
    badges: ["giftable"],
    variants: [{ name: "Eye Set", sku: "KEIG-3", price: 158000, stock: 55 }],
    imageSeeds: 2,
    rating: { avg: 4.5, count: 143 },
    totalSold: 780,
  },
];

function buildImages(
  slug: string,
  name: string,
  seeds: number,
): Array<{ url: string; alt: string; order: number }> {
  const count = Math.max(1, Math.min(seeds, 3));
  const images: Array<{ url: string; alt: string; order: number }> = [];
  for (let i = 0; i < count; i++) {
    const suffix = i === 0 ? "" : `-${i + 1}`;
    images.push({
      url: `https://picsum.photos/seed/${slug}${suffix}/800/800`,
      alt: name,
      order: i,
    });
  }
  return images;
}

export async function seedProducts(): Promise<{ created: number; skipped: number }> {
  const categories = await Category.find({
    slug: { $in: productEntries.map((p) => p.categorySlug) },
  })
    .select({ slug: 1 })
    .lean();
  const catBySlug = new Map(categories.map((c) => [c.slug, c._id]));

  const existing = await Product.find({ slug: { $in: productEntries.map((p) => p.slug) } })
    .select({ slug: 1 })
    .lean();
  const existingSlugs = new Set(existing.map((p) => p.slug));

  let created = 0;
  let skipped = 0;

  for (const entry of productEntries) {
    if (existingSlugs.has(entry.slug)) {
      skipped++;
      continue;
    }
    const categoryId = catBySlug.get(entry.categorySlug);
    if (!categoryId) {
      skipped++;
      continue;
    }

    await Product.create({
      name: entry.name,
      slug: entry.slug,
      description: entry.description,
      shortDescription: entry.shortDescription,
      categoryId,
      brand: entry.brand,
      basePrice: entry.basePrice,
      comparePrice: entry.comparePrice,
      tags: entry.tags,
      badges: entry.badges,
      skinTypes: entry.skinTypes ?? [],
      ingredients: entry.ingredients ?? [],
      allergens: entry.allergens ?? [],
      images: buildImages(entry.slug, entry.name, entry.imageSeeds ?? 2),
      variants: entry.variants.map((v) => ({
        name: v.name,
        sku: v.sku,
        price: v.price,
        comparePrice: v.comparePrice,
        stock: v.stock,
        reservedStock: 0,
        isActive: true,
      })),
      rating: { avg: entry.rating.avg, count: entry.rating.count },
      totalSold: entry.totalSold,
      isFeatured: entry.isFeatured ?? false,
      isActive: true,
      seoMeta: {
        title: `${entry.name} — GlowCart`,
        description: entry.shortDescription,
      },
    });
    created++;
  }

  return { created, skipped };
}
